title: Hello World ! Soy sebaleoperez
description: "Blog personal sobre desarrollo, .NET, Web3 y m√°s"
  
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sebaleoperez.github.io"

# Author Settings
author: sebaleoperez # add your name
author-img: sebaleoperez.png # add your photo
about-author: <strong class="accent">Web</strong>, <strong class="accent">Mobile</strong> and <strong class="accent">Blockchain</strong> üßë‚Äçüíª Developer.<br />Kind of <em>basketball player</em>.
social-x: sebaleoperez # add your X handle
social-github: sebaleoperez # add your Github handle
social-linkedin: sebaleoperez # add your Linkedin handle
social-email: sebastian.leo.perez@outlook.com.ar # add your Email address
social-instagram: sebaleoperez # add your instagram handle

# Disqus Comments
# Create your site at https://disqus.com and put your shortname below
disqus: sebaleoperez # your Disqus shortname

# Google Analytics 4 ‚Äî Get your Measurement ID at https://analytics.google.com
# Format: G-XXXXXXXXXX
analytics: # G-XXXXXXXXXX

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed

paginate: 20
paginate_path: "/page/:num"

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]